"""Generate chriz-sod-remix/lib/comp220_lists.tpa (lives in research/scripts/).

Policy (design LOCKED, docs/design/chapters/02-coastway.md + 3a rev 2026-07-10):
  BD1100 keeps: Semahl's 5 BDATKSEM (9,10,46,47,48); dwarf-siege pushover
    (5 quest wight BD_DOD_WIGHT1, zombies 6,7,8,81); pushover B (26,27,30,31);
    lone mummy 86; umber hulks 11,12,13. Everything else hostile -> cut.
  BD1200 keeps in place: horde-room weak members (55,56,57,25,26), ghast 95,
    SW skeleton pushover (18,19,20,60). The six Crimson-Pool BDDEAD01
    ("Drowned in Blood" 4,5,6,7,103,104) are CUT (playtest: monotonous
    6-of-one filler); their XP flows into the ledger chunk.
  BD1200 moves: 6 shambler horde-ins (64,65,71,72,73,74 -> vacated cluster-A
    spots), ghast partner 70 -> (2006,1237); the honor guard (108,109,78,96)
    stands ON four vacated drowned coords (user rule 2026-07-10: never place
    where no enemy was placed before - the first attempt interpolated the
    Door08->Secret02 corridor and landed on impassable searchmap void).
  Critters (BDBATNC/BDRATNC) and quest/boss actors are never touched.

ARE SOURCE: the WeiDU backup of component 220 (pre-220 pristine files) when
present - the dev override is post-220 (schedules zeroed, actors moved), and
the lists' CRE@X@Y keys must match what a REinstall sees after WeiDU restores
the backup. CRE kill-XP still reads from override (CREs untouched by 220).
"""
import struct, os, glob, collections

GAME = r"C:\Games\Baldur's Gate II Enhanced Edition modded - dev eet install"
OVR = os.path.join(GAME, "override")
BAK = os.path.join(GAME, r"weidu_external\backup\chriz-sod-remix\220")
OUT = r"C:\src\private\chriz-sod-rebalance\chriz-sod-remix\lib\comp220_lists.tpa"

def cstr(b):
    z = b.find(b'\x00')
    if z >= 0: b = b[:z]
    return b.decode('latin1','replace').strip()

def load(area):
    bak = os.path.join(BAK, area + '.are')
    if os.path.isfile(bak):
        print(f"  {area}: using pre-220 backup ARE")
        return open(bak,'rb').read()
    for p in glob.glob(os.path.join(OVR,'*')):
        if os.path.basename(p).lower() == (area+'.are').lower():
            print(f"  {area}: WARNING - no 220 backup found, using override "
                  f"(only valid if 220 is NOT installed)")
            return open(p,'rb').read()
    raise SystemExit(f"{area} not found")

def actors(b):
    off = struct.unpack_from('<I',b,0x54)[0]; cnt = struct.unpack_from('<H',b,0x58)[0]
    out={}
    for i in range(cnt):
        base = off+i*0x110
        out[i]=dict(name=cstr(b[base:base+32]),
            x=struct.unpack_from('<h',b,base+0x20)[0],
            y=struct.unpack_from('<h',b,base+0x22)[0],
            cre=cstr(b[base+0x80:base+0x88]).upper())
    return out

def killxp(cre):
    for p in glob.glob(os.path.join(OVR,'*')):
        if os.path.basename(p).lower()==cre.lower()+'.cre':
            return struct.unpack_from('<I',open(p,'rb').read(),0x14)[0]
    raise SystemExit(f"CRE {cre} not in override")

CRITTERS = {'BDBATNC','BDRATNC'}
NONHOSTILE = {'BDDCLER1','BDDCLER2','BDDCLER3','BDDEEP','BDDODWD','BDSEMAHL',
              'BDCOLDH','BDBRONZE','BDDLICH','BDSCRY'}

KEEP_1100 = {5,6,7,8,81, 9,10,46,47,48, 26,27,30,31, 86, 11,12,13}
KEEP_1200 = {55,56,57,25,26, 95, 18,19,20,60}
MOVES_1200 = {  # idx: (newx, newy, orient)  orient 4 = face W
    64:(2561,1636,4), 73:(2719,2175,4), 74:(2412,1813,4),
    65:(2665,1992,4), 71:(2801,2074,4), 72:(2741,1838,4),
    70:(2006,1237,4),
    # honor guard on vacated drowned coords (searchmap-walkable by
    # construction): skeleton warriors centre, mummies on the flanks
    108:(3482,1682,4), 109:(3471,1632,4), 78:(3533,1643,4), 96:(3315,1772,4),
}

xpcache={}
def xp(cre):
    if cre not in xpcache: xpcache[cre]=killxp(cre)
    return xpcache[cre]

lines=[]
lines.append("// GENERATED by research/scripts/gen220.py (2026-07-10 rev: drowned cut,")
lines.append("// honor guard onto vacated drowned coords) from the pre-220 pristine AREs.")
lines.append("// Keys are CRE@X@Y of vanilla placed actors; regenerate rather than hand-edit.")
lines.append("")
totals={}
for area, keeps, moves in (('bd1100',KEEP_1100,{}), ('bd1200',KEEP_1200,MOVES_1200)):
    b=load(area); acts=actors(b)
    cut=[]; keepxp=0; cutxp=0; total=0
    for i,a in acts.items():
        if not a['cre'] or a['cre'] in CRITTERS or a['cre'] in NONHOSTILE: continue
        total += xp(a['cre'])
        if i in keeps or i in moves:
            keepxp += xp(a['cre'])
        else:
            cut.append((i,a)); cutxp += xp(a['cre'])
    totals[area]=(total,keepxp,cutxp,len(cut))
    lines.append(f"// ---- {area}: {len(cut)} cuts (garrison {total} xp, kept {keepxp}, cut {cutxp}) ----")
    for i,a in cut:
        lines.append(f'OUTER_SPRINT $csr_cut_{area}(~{a["cre"]}@{a["x"]}@{a["y"]}~) ~1~   // idx{i} {a["name"]}')
    lines.append(f"OUTER_SET csr_cutn_{area} = {len(cut)}")
    lines.append("")
    if moves:
        lines.append(f"// ---- {area}: {len(moves)} repositioned actors ----")
        for i,(nx,ny,o) in sorted(moves.items()):
            a=acts[i]
            key=f'{a["cre"]}@{a["x"]}@{a["y"]}'
            lines.append(f'OUTER_SPRINT $csr_mvx_{area}(~{key}~) ~{nx}~   // idx{i} {a["name"]} -> ({nx},{ny})')
            lines.append(f'OUTER_SPRINT $csr_mvy_{area}(~{key}~) ~{ny}~')
            lines.append(f'OUTER_SPRINT $csr_mvo_{area}(~{key}~) ~{o}~')
        lines.append(f"OUTER_SET csr_movn_{area} = {len(moves)}")
        lines.append("")

gt = sum(t[0] for t in totals.values()); gk = sum(t[1] for t in totals.values()); gc = sum(t[2] for t in totals.values())
# AddexperienceParty DIVIDES among living party members (user-verified in-game
# 2026-07-12; IESDP was right, the earlier per-member assumption was wrong).
# So the chunk is the PARTY-TOTAL 80% of the cut — the engine then splits it
# exactly like the kill XP it replaces (party-size-faithful, solo included).
chunk = int(round(gc*0.8/100.0))*100
lines.append(f"// XP ledger: garrison total {gt}, kept {gk}, cut {gc}.")
lines.append(f"// Compensation = cut * 0.8 as ONE party-total AddexperienceParty (the engine")
lines.append(f"// divides it, matching kill-XP economics; ~{int(round(chunk/6.0))}/char at a party of 6)")
lines.append(f"// = {gc} * 0.8 rounded to 100 -> {chunk}, on the lich clean-kill.")
lines.append(f"OUTER_SET csr_xp_chunk = {chunk}")
lines.append("")
open(OUT,'w',newline='\n').write('\n'.join(lines))
print(f"wrote {OUT}")
for a,(t,k,c,n) in totals.items(): print(f"  {a}: total={t} keep={k} cut={c} ncut={n}")
print(f"  chunk={chunk}")
