"""Generate chriz-sod-remix/lib/restmap.tpa — WeiDU associative array mapping every
possible per-hour rest-interrupt chance 1..99 to its 5x-felt-reduced value.

Same formula as wave1_rest_table.py (design docs/design/wave1/01):
felt(c) = 1-(1-c/100)^8 ; new = max(1, round(invert(felt/5))).
Values >= 100 are never patched (guarded in the tp2) — 100 is the BDNOREST
"cannot rest" convention and must not be touched.
"""
import pathlib

def felt(c: float) -> float:
    return (1 - (1 - c / 100) ** 8) * 100

def invert(f: float) -> float:
    return (1 - (1 - f / 100) ** (1 / 8)) * 100

lines = ["// GENERATED by research/scripts/gen_restmap_tpa.py -- do not hand-edit",
         "ACTION_DEFINE_ASSOCIATIVE_ARRAY csr_restmap BEGIN"]
for c in range(1, 100):
    new = max(1, round(invert(felt(c) / 5)))
    lines.append(f"  {c} => {new}")
lines.append("END")

out = pathlib.Path(__file__).resolve().parents[2] / "chriz-sod-remix" / "lib" / "restmap.tpa"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(lines) + "\n", encoding="ascii")
print(f"wrote {out} ({len(lines)} lines); spot-checks:",
      {c: max(1, round(invert(felt(c) / 5))) for c in (3, 5, 6, 7, 8, 9, 10, 12, 18)})
