"""Generate comp230_lists.tpa + comp240_lists.tpa (road-north quick-win pass).

Design: docs/design/chapters/03-roadnorth.md "Quick-win pass" (CONFIRMED
2026-07-11). Cut selection by verified actor index (scratchpad ch9 dumps,
2026-07-11), emitted as CRE@X@Y keys like gen220.

  comp230 (main line):
    BD7100: hobgoblins x16, orcs x14, beetles x8, displacer pack x6,
      small spiders x8 (both nests keep their gargantuan+sword elites),
      troll thin-out x11 (clusters: C 11->4, D 6->4, B 8->6, A untouched).
    BD2000: bombardier beetles x5, worgs x2, stray wight x1 (siege
      pickets and the whole scripted crusader battle untouched).
    BD2010: goblin chaff x27 (keeps chieftain, shaman, 3 elite warriors,
      3 warriors around the chieftain).
  comp240 (optional Forest-of-Wyrms loop):
    BD7200: bugbear door-guards x11, displacer pack x7, dire wolves x5,
      small spiders x5 (wyverns, phase spiders + astral, hill giant stay).
    BD7230: the 6 post-Neothelid invisible ambushers (region script
      BD7230AM goes permanently false once they never spawn).
    BD7220 (bugbear cave) is REMOVED by unreachability (comp240 retargets
      the only two travel regions pointing at it); its hostile XP + the
      quest-only Greater Shadow are ledgered here without touching the file.

ARE SOURCE: WeiDU backups of the component (pre-patch pristine files) when
present, else override (valid only while 230/240 are NOT installed).
"""
import struct, os, glob

GAME = r"C:\Games\Baldur's Gate II Enhanced Edition modded - dev eet install"
OVR = os.path.join(GAME, "override")
BAKROOT = os.path.join(GAME, r"weidu_external\backup\chriz-sod-remix")
OUT230 = r"C:\src\private\chriz-sod-rebalance\chriz-sod-remix\lib\comp230_lists.tpa"
OUT240 = r"C:\src\private\chriz-sod-rebalance\chriz-sod-remix\lib\comp240_lists.tpa"

def cstr(b):
    z = b.find(b'\x00')
    if z >= 0: b = b[:z]
    return b.decode('latin1', 'replace').strip()

def load(area, comp):
    bak = os.path.join(BAKROOT, str(comp), area + '.are')
    if os.path.isfile(bak):
        print(f"  {area}: using pre-{comp} backup ARE")
        return open(bak, 'rb').read()
    for p in glob.glob(os.path.join(OVR, '*')):
        if os.path.basename(p).lower() == (area + '.are').lower():
            print(f"  {area}: WARNING - no {comp} backup found, using override "
                  f"(only valid if {comp} is NOT installed)")
            return open(p, 'rb').read()
    raise SystemExit(f"{area} not found")

def actors(b):
    off = struct.unpack_from('<I', b, 0x54)[0]
    cnt = struct.unpack_from('<H', b, 0x58)[0]
    out = {}
    for i in range(cnt):
        base = off + i * 0x110
        out[i] = dict(name=cstr(b[base:base+32]),
                      x=struct.unpack_from('<h', b, base+0x20)[0],
                      y=struct.unpack_from('<h', b, base+0x22)[0],
                      cre=cstr(b[base+0x80:base+0x88]).upper())
    return out

xpcache = {}
def killxp(cre):
    if cre not in xpcache:
        for p in glob.glob(os.path.join(OVR, '*')):
            if os.path.basename(p).lower() == cre.lower() + '.cre':
                d = open(p, 'rb').read()
                xpcache[cre] = (struct.unpack_from('<I', d, 0x14)[0], d[0x270])
                break
        else:
            raise SystemExit(f"CRE {cre} not in override")
    return xpcache[cre]

# ---- cut selections (verified actor indices, ch9 dumps 2026-07-11) ----
CUTS = {
    # comp230
    'bd7100': ({156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,  # hobgoblins
                48,49,50,51,52,53,54,55,56,116,117,118,119,120,                    # orcs
                135,136,137,138,139,140,141,142,                                   # beetles
                121,122,123,124,125,126,                                           # displacers
                87,88,89,90,127,128,129,130,                                       # small spiders
                35,36,37,38,45,46,144,145,146,147,148}, 255),                      # troll thin-out
    'bd2000': ({135,136,137,138,139, 86,87, 1}, 255),
    'bd2010': ({3,4,5,6,7,8,9,10,19, 12,13,14,15,17,18,
                24,25,26,27,28,29,30,31,32,33,34,35}, 255),
    # comp240
    'bd7200': ({16,17,18,19,20,52,53,54,55,56,57,                                  # bugbears
                36,37,38,39,40,41,58,                                              # displacers
                13,14,47,48,49,                                                    # dire wolves
                0,1,2,3,4}, 255),                                                  # small spiders
    'bd7230': ({5,7,9,10,15,16}, 128),   # ambushers are EA=NEUTRAL until sprung
}

def emit(outpath, comp, areas, extra_field=0, extra_note=""):
    lines = [f"// GENERATED by research/scripts/gen_ch9.py (2026-07-11) from the",
             f"// pre-{comp} pristine AREs. Keys are CRE@X@Y of vanilla placed actors;",
             "// regenerate rather than hand-edit.", ""]
    total_cut = 0
    for area in areas:
        idxs, want_ea = CUTS[area]
        b = load(area, comp)
        acts = actors(b)
        missing = idxs - set(acts)
        if missing:
            raise SystemExit(f"{area}: cut indices not present: {missing}")
        cutxp = 0
        lines.append(f"// ---- {area}: {len(idxs)} cuts ----")
        for i in sorted(idxs):
            a = acts[i]
            xp, ea = killxp(a['cre'])
            if ea != want_ea:
                raise SystemExit(f"{area} idx{i} {a['cre']}: EA={ea}, expected {want_ea}")
            cutxp += xp
            lines.append(f'OUTER_SPRINT $csr_cut_{area}(~{a["cre"]}@{a["x"]}@{a["y"]}~) ~1~'
                         f'   // idx{i} {a["name"]} ({xp} xp)')
        lines.append(f"OUTER_SET csr_cutn_{area} = {len(idxs)}")
        lines.append(f"// {area} cut kill-XP: {cutxp}")
        lines.append("")
        total_cut += cutxp
        print(f"  {area}: {len(idxs)} cuts, {cutxp} xp")
    total_cut += extra_field
    chunk = int(round(total_cut * 0.8 / 6.0 / 100.0)) * 100
    lines.append(f"// XP ledger: cut kill-XP {total_cut}{extra_note}.")
    lines.append("// Compensation = cut * 0.8 / 6 (party-of-6 ledger baseline,")
    lines.append(f"// AddexperienceParty grants per member) rounded to 100 -> {chunk}/char.")
    lines.append(f"OUTER_SET csr_xp_chunk_{comp} = {chunk}")
    lines.append("")
    open(outpath, 'w', newline='\n').write('\n'.join(lines))
    print(f"  -> chunk_{comp} = {chunk}  ({outpath})")

print("comp230:")
emit(OUT230, 230, ('bd7100', 'bd2000', 'bd2010'))

print("comp240:")
# BD7220 becomes unreachable: ledger its hostile XP + the quest-only
# Greater Shadow (3000) without patching the file.
b7220 = load('bd7220', 240)
h = 0
for i, a in actors(b7220).items():
    if not a['cre']: continue
    xp, ea = killxp(a['cre'])
    if ea == 255: h += xp
    elif a['cre'] == 'BDSHADOW': h += xp
print(f"  bd7220 (unreachable): ledgered {h} xp (hostiles + Greater Shadow)")
emit(OUT240, 240, ('bd7200', 'bd7230'), extra_field=h,
     extra_note=f" (incl. {h} from the unreachable BD7220: hostiles + quest shadow)")
